### ISSUE TITLE
Question - How to connect to the sensu api using the sensu-cli?

### ISSUE THREAD

**Issue by 030** [agent462/sensu-cli#48]
sensu-cli check list
An HTTP error occurred.  Check your settings. Connection refused - connect(2)

/home/user/.sensu/settings.rb.

host  "company.sheva.io"
port  "4567"
ssl   false
read_timeout 20
open_timeout 20
user ""
password ""

uchiwa.json contains an empty pass and username as well

**Comment by agent462** [comment]
I won't be able to solve why you are getting a connection refused.  This is usually because of a firewall or nothing is listening on the IP:Port you are specifying.

You can check that the port is listening with something like sudo netstat -tulpn | grep 4567

Other than that make sure iptables, firewalld or whatever physical firewall you have has the port open.

**Comment by 030** [comment]
I did a telnet and it is able to connect

**Comment by 030** [comment]
A `/home/user/.sensu/settings.rb` was created initially, subsequently the correct values were put in `/home/user/.sensu/settings.rb.`, while it should have been `/home/user/.sensu/settings.rb`. The issue was caused by the `.`
