### ISSUE TITLE
Connect to message broker instead of api

### ISSUE THREAD

**Issue by 030** [agent462/sensu-cli#49]
The sensu-client connects to the RabbitMQ server instead of the API directly. Would it be possible to let the sensu-cli connect to the messagebroker instead of the api directly?

**Comment by agent462** [comment]
It's not possible.  The queue is used to pass messages back and forth between clients and the server.  The server processes all of this data and then stores it in redis.  Sensu API allows access to this stored state and interaction with the Sensu Server.  Sensu-cli uses the Sensu API for interaction so that it keeps the contract given by the API.  This assists in feature parody.
